apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyapp
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm/python-repo
    repoURL: https://github.com/danielsidauruk/cloud-ops.git
    targetRevision: HEAD
    # helm:
    #   values: |-
    #     resources:
    #       limits:
    #         cpu: 50m
    #         memory: 128Mi
    #       requests:
    #         cpu: 50m
    #         memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
